new: mkenv ok

diff --git a/new_arch/mkenv b/new_arch/mkenv
--- a/new_arch/mkenv
+++ b/new_arch/mkenv
@@ -22,22 +22,26 @@ main()
 {
 	iname=$1;
 	num=$2;
-	kind=$3;
 
-	for envname in os httpd jboss systemctl
+	for envname in os httpd jboss systemctl.jboss systemctl.httpd
 	do
 		bfile="$BASE/$envname.env.base";
 		if [ -s "$bfile" ]
 		then
-			cat $bfile | \
+		cat $bfile | \
 			case $envname in
 			os ) mk_os_env $iname $num ;;
 			httpd ) mk_httpd_env $iname $num ;;
 			jboss ) mk_jboss_env $iname $num ;;
-			systemctl ) mk_systemctl_env $kind $iname $num ;;
-			esac | \
-			>
-		> $NEW/$envname.env
+			systemctl.jboss ) mk_systemctl_env "jboss" $iname $num ;;
+			systemctl.httpd ) mk_systemctl_env "httpd" $iname $num ;;
+			* ) echo "ERROR: $envname case string is NOT defined in $MYNAME:main()" 1>&2; exit 1;;
+			esac >$NEW/$envname.env
+		else
+			"ERROR: $bfile is NOT exist";
+			exit 1;
+		fi
+	done
 }
 
 mk_os_env() # iname num
@@ -45,11 +49,10 @@ mk_os_env() # iname num
 	iname="$1";
 	num="$2";
 
-	envname=os
 	uid="`expr $OS_USER_ID_BASE + $OS_USER_ID_OFFSET \* $num`";
 	gid="`expr $OS_GROUP_ID_BASE + $OS_GROUP_ID_OFFSET \* $num`";
 
-	cat $BASE/$envname.env.base | sed \
+	sed \
 		-e 's[__HEADER_SCRIPT__['$MYNAME'[g' \
 		-e 's[__HEADER_ARGS__['"$MYARGS"'[g' \
 		-e 's[__HEADER_DATE__['`date $DATE_TIME_FMT`'[g' \
@@ -58,7 +61,7 @@ mk_os_env() # iname num
 		-e 's[__OS_GROUP_NAME__['${iname}OG'[g' \
 		-e 's[__OS_GROUP_ID__['${gid}'[g' \
 		-e 's[__OS_USER_HOME__['/$PROJ_NAME/home/${iname}'[g' \
-		> $NEW/$envname.env
+		;
 }
 
 mk_httpd_env() # iname num
@@ -66,7 +69,6 @@ mk_httpd_env() # iname num
 	iname="$1";
 	num="$2";
 
-	envname=httpd
 
 	. $NEW/os.env
 
@@ -79,14 +81,14 @@ mk_httpd_env() # iname num
 	listenport="`expr $HTTPD_LISTEN_PORT_BASE + $num`";
 	workerport="`expr $HTTPD_WORKER_SERVER1_PORT_BASE + $HTTPD_WORKER_SERVER1_PORT_OFFSET \* $num`";
 
-	cat $BASE/$envname.env.base | sed \
+	sed \
 		-e 's[__HEADER_SCRIPT__['$MYNAME'[g' \
 		-e 's[__HEADER_ARGS__['"$MYARGS"'[g' \
 		-e 's[__HEADER_DATE__['`date $DATE_TIME_FMT`'[g' \
 		-e 's[__HTTPD_TOPDIR__['${topdir}'[g' \
 		-e 's[__HTTPD_LISTEN_PORT__['${listenport}'[g' \
 		-e 's[__HTTPD_WORKER_SERVER1_PORT__['${workerport}'[g' \
-		> $NEW/$envname.env
+		;
 }
 
 get_java_home() # void
@@ -109,8 +111,6 @@ mk_jboss_env() # iname num
 	iname="$1";
 	num="$2";
 
-	envname=jboss
-
 	. $NEW/os.env
 
 	HTTPD_LISTEN_PORT_BASE=81
@@ -130,7 +130,7 @@ mk_jboss_env() # iname num
 
 	JBOSS_DS_SERVER_NAME="127.0.0.1";
 
-	cat $BASE/$envname.env.base | sed \
+	sed \
 		-e 's[__HEADER_SCRIPT__['$MYNAME'[g' \
 		-e 's[__HEADER_ARGS__['"$MYARGS"'[g' \
 		-e 's[__HEADER_DATE__['`date $DATE_TIME_FMT`'[g' \
@@ -150,7 +150,7 @@ mk_jboss_env() # iname num
 		-e 's[__JBOSS_DS_SERVER_NAME__['${JBOSS_DS_SERVER_NAME}'[g' \
 		-e 's[__JBOSS_DS_DB_NAME__['${iname}DB'[g' \
 		-e 's[__JBOSS_DS_USER_NAME__['${iname}DU'[g' \
-		> $NEW/$envname.env
+		;
 }
 
 mk_systemctl_env() # kind iname num
@@ -159,16 +159,13 @@ mk_systemctl_env() # kind iname num
 	iname="$2";
 	num="$3";
 
-	envname=systemctl
-	
-	cat $BASE/$envname.env.base |\
- 		sed \
+ 	sed \
 		-e 's[__HEADER_SCRIPT__['$MYNAME'[g' \
 		-e 's[__HEADER_ARGS__['"$MYARGS"'[g' \
 		-e 's[__HEADER_DATE__['`date $DATE_TIME_FMT`'[g' \
 		\
 		-e 's[__SYSCONFIG_NAME__['${kind}-${iname}'[g' \
-		> $NEW/$envname.env
+		;
 }
 
 main $*;
